coin_handler/urls.py
from django.urls import path

from . import views

app_name = 'coin_handler'
urlpatterns = [
    path('index/<int:person_id>', views.index, name='index'),
    path('log/<int:person_id>', views.log, name='log'),
    path('send_cash/<int:person_id>', views.send_cash, name='send cash'),
    path('process_cash_sending/<int:person_id>', views.process_cash_sending, name='process cash sending'),
    path('login', views.login, name='login'),
    path('process_login', views.process_login, name='process login'),
]

ripio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('coin_handler/', include('coin_handler.urls')),
    path('admin/', admin.site.urls),
]

coin_handler/models.py
from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=30)


class Currency(models.Model):
    name = models.CharField(max_length=30)


class AmountOfCurrency(models.Model):
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE)
    owner = models.ForeignKey(Person, on_delete=models.CASCADE)
    amount = models.IntegerField(default=0)

    class Meta:
        unique_together = ('currency', 'owner')


class LogLine(models.Model):
    actor = models.ForeignKey(Person, on_delete=models.CASCADE)
    date = models.DateTimeField()
    text = models.CharField(max_length=200)

coin_handler/views.py
from django.db import transaction
from django.shortcuts import render, get_object_or_404
from django.utils.datetime_safe import date

from coin_handler.models import AmountOfCurrency, Person, LogLine, Currency


def index(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    person_currencies = AmountOfCurrency.objects.filter(owner=person_id)
    context = {
        'person': person,
        'person_currencies': person_currencies,
    }
    return render(request, 'coin_handler/index.html', context)


def log(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    user_log_lines = LogLine.objects.filter(actor=person_id)
    context = {
        'person': person,
        'user_log_lines': user_log_lines,
    }
    return render(request, 'coin_handler/log.html', context)


def send_cash(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    person_currencies = AmountOfCurrency.objects.filter(owner=person_id)
    possible_addresses = Person.objects.exclude(id=person_id)
    context = {
        'person': person,
        'person_currencies': person_currencies,
        'possible_addresses': possible_addresses,
    }
    return render(request, 'coin_handler/send_cash.html', context)


def process_cash_sending(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    person_currencies = AmountOfCurrency.objects.filter(owner=person_id)
    possible_addresses = Person.objects.exclude(id=person_id)
    addressee_id = request.POST.get('addressee', False)
    currency_id = request.POST.get('currency', False)
    amount = request.POST.get('amount', False)
    currency = get_object_or_404(Currency, pk=currency_id)
    addressee = get_object_or_404(Person, pk=addressee_id)

    error_message = False
    if not amount:
        error_message = "Please, set an amount to send."
    if not currency_id:
        error_message = "Currency not set. Again... good try :)"
    if not addressee_id:
        error_message = "Addressee not set. Good try though :)"
    if error_message:
        context = {
            'person': person,
            'person_currencies': person_currencies,
            'result_message': error_message,
            'possible_addresses': possible_addresses,
        }
        return render(request, 'coin_handler/send_cash.html', context)

    amount = int(amount)

    with transaction.atomic():
        try:
            addressee_currency_to_augment = AmountOfCurrency.objects.select_for_update()\
                .get(currency=currency_id, owner=addressee_id)
            addressee_currency_to_augment.amount += amount
        except AmountOfCurrency.DoesNotExist:
            addressee_currency_to_augment = AmountOfCurrency.objects.create(currency=currency, owner=addressee,
                                                                            amount=amount)

        sender_currency_to_diminish = get_object_or_404(AmountOfCurrency.objects.select_for_update(),
                                                        currency=currency_id, owner=person_id)
        sender_currency_to_diminish.amount -= amount
        if sender_currency_to_diminish.amount < 0:
            context = {
                'person': person,
                'person_currencies': person_currencies,
                'result_message': "You've not enough of that currency.",
                'possible_addresses': possible_addresses,
            }
            return render(request, 'coin_handler/send_cash.html', context)

        addressee_currency_to_augment.save()
        sender_currency_to_diminish.save()

    text = 'Sent %s %s to %s.' % (amount, currency.name, addressee.name)
    LogLine.objects.create(actor=person, date=date.today(), text=text)
    text = 'Received %s %s from %s.' % (amount, currency.name, person.name)
    LogLine.objects.create(actor=addressee, date=date.today(), text=text)

    context = {
        'person': person,
        'person_currencies': person_currencies,
        'result_message': "Success!",
        'possible_addresses': possible_addresses,
    }
    return render(request, 'coin_handler/send_cash.html', context)


def login(request):
    people = Person.objects.all()
    context = {'people': people, }
    return render(request, 'coin_handler/login.html', context)


def process_login(request):
    person_id = request.POST.get('person', False)
    if not person_id:
        people = Person.objects.all()
        context = {'people': people,
                   'result_message': 'You must select a person', }
        return render(request, 'coin_handler/login.html', context)
    return index(request, person_id)

coin_handler/templates/coin_handler/index.html
<h2>Your currencies amounts</h2>

<table>
    <tr>
        <th>Currency</th>
        <th>Amount</th>
    </tr>
    {% for person_currency in person_currencies %}
    <tr>
        <td>{{ person_currency.currency.name }}</td>
        <td>{{ person_currency.amount }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'coin_handler:log' person.id %}">Log</a>
|
<a href="{% url 'coin_handler:send cash' person.id %}">Send cash</a>

coin_handler/templates/coin_handler/log.html
<h2>Your Log</h2>

<table>
    <tr>
        <th>actor</th>
        <th>text</th>
        <th>date</th>
    </tr>
    {% for user_log_line in user_log_lines %}
    <tr>
        <td>{{ user_log_line.actor.name }}</td>
        <td>{{ user_log_line.text }}</td>
        <td>{{ user_log_line.date }}</td>
    </tr>
    {% endfor %}
</table>

<a href="{% url 'coin_handler:index' person.id %}">Back</a>

coin_handler/templates/coin_handler/login.html
<h2>Log in</h2>

<form action="{% url 'coin_handler:process login' %}" method="post">
    {% csrf_token %}

    <select name="person">
        {% for person in people %}
        <option value="{{ person.id }}">{{ person.name }}</option>
        {% endfor %}
    </select>

    <input type="submit" value="Send">
</form>

{% if result_message %}<p><strong>{{ result_message }}</strong></p>{% endif %}

coin_handler/templates/coin_handler/send_cash.html
<h2>Send Cash</h2>

<form action="{% url 'coin_handler:process cash sending' person.id %}" method="post">
    {% csrf_token %}

    <select name="addressee">
        {% for addressee in possible_addresses %}
        <option value="{{ addressee.id }}">{{ addressee.name }}</option>
        {% endfor %}
    </select>

    <select name="currency">
        {% for person_currency in person_currencies %}
        <option value="{{ person_currency.currency.id }}">{{ person_currency.currency.name }}</option>
        {% endfor %}
    </select>
    <input type="number" placeholder="amount" name="amount">

    <input type="submit" value="Send">
</form>

{% if result_message %}<p><strong>{{ result_message }}</strong></p>{% endif %}

<a href="{% url 'coin_handler:index' person.id %}">Back</a>